[providers]

[providers.openai]
base_url = "https://api.openai.com/v1"
models = ["gpt-3.5-turbo", "gpt-4", "gpt-4o"]

[providers.anthropic]
base_url = "https://api.anthropic.com/v1"
models = [
    "claude-3-5-sonnet-latest",
    "claude-3-7-sonnet-latest", 
    "claude-3-5-haiku-latest"
]

[providers.deepseek]
base_url = "https://api.deepseek.com/v1"
models = ["deepseek-chat", "deepseek-reasoner"]

[providers.bedrock]
base_url = ""
models = ["anthropic.claude-v2", "amazon.titan-text-express-v1"]

[providers.ollama]
base_url = "http://localhost:11434"
models = ["llama2", "codellama"]

infrastructure_types = [
  "Terraform",
  "CloudFormation", 
  "Kubernetes",
  "Docker",
  "CI/CD Pipeline",
  "OPA Policy",
  "Azure Resource Manager (ARM)"
]

default_provider = "deepseek"
default_model = "deepseek-reasoner"
